const ShopActionTypes = {
  UPDATE_COLLECTIONS_START: 'UPDATE_COLLECTIONS_START',
  UPDATE_COLLECTIONS_SUCCESS: 'UPDATE_COLLECTIONS_SUCCESS',
  UPDATE_COLLECTIONS_FAILURE: 'UPDATE_COLLECTIONS_FAILURE'
};

export default ShopActionTypes;
