export const UserActionTypes = {
  USER_LOGIN_START: 'USER_LOGIN/START',
  USER_LOGIN_SUCCESS: 'USER_LOGIN/SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN/FAILURE',
  GOOGLE_LOGIN_START: 'GOOGLE_LOGIN/START',
  GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN/SUCCESS',
  GOOGLE_LOGIN_FAILURE: 'GOOGLE_LOGIN/FAILURE',
  USER_SIGNUP_START: 'USER_SIGNUP/START',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP/SUCCESS',
  USER_SIGNUP_FAILURE: 'USER_SIGNUP/FAILURE',
  USER_LOGOUT_START: 'USER_LOGOUT/START',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT/SUCCESS',
  USER_LOGOUT_FAILURE: 'USER_LOGOUT/FAILURE',
};
